services:
  - type: web
    name: tgaz-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    plan: free
    envVars:
      - key: TOKEN
        value: 7971701925:AAGr7HiOrCcnKeIxMjrLzisiX4LpSLMg-b4
